### ISSUE TITLE
Requesting to minimize status time line

### ISSUE THREAD

**Issue by kk8152** [kk8825/WhatsupNew-Development#3]
Dear kk8825,
                 Your applications features are great. my suggestion to minimize the status time to 30 seconds. kindly review and implement the enhancement. thank you..

**Comment by kk8825** [comment]
Dear kk8152,
                  thanks for your idea we added your suggestion.. keep supporting us.

**Comment by kk8825** [comment]
Dear kk8152,
                 Your suggestion was added. keep supporting us.
